version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp:pass@postgres/todos
  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: pass
    ports:
      - "10030:5432"